version: '3'

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: explain-nginx
    depends_on:
      - api
      - face
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf

  api:
    build:
      context: api/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
    command: yarn run start:dev
    container_name: explain-api

  face:
    build:
      context: face/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./face:/app
    command: npm run dev
    container_name: explain-face