import { GrammarAliases } from '../grammarTypes'
import { StoryConfigT } from '../storyTypes'

export const sampleText2: StoryConfigT.Story = {
	enHeader: "The Rajah's Diamond",
	ruHeader: 'Бриллиант раджи',
	level: ['a1'],
	paragraphs: [
		{
			type: 'paragraph',
			sentences: [
				{
					type: 'sentence',
					id: 1,
					sentenceParts: [
						{
							id: 1,
							type: 'word',
							phraseIds: [1],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'These',
								rusWord: 'Эти',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 2,
							type: 'word',
							phraseIds: [2],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Subject',
								engWord: 'talents',
								rusWord: 'таланты',
								rusExplanation: '',
								enTranscription: 'ˈtælənts',
								usTranscription: 'ˈtælənts',
							},
						},
						{
							type: 'punctuation',
							text: ', ',
						},
						{
							id: 3,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Conjunction',
								partOfSpeech: 'Conjunction',
								engWord: 'and',
								rusWord: 'и',
								rusExplanation: '',
								enTranscription: 'ænd',
								usTranscription: 'ænd',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 4,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Article',
								partOfSpeech: 'Modifier',
								engWord: 'a',
								rusWord: '',
								rusExplanation:
									'Артикль, указывающий на неопределённое существительное.',
								enTranscription: 'ə',
								usTranscription: 'ə',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 5,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Object',
								engWord: 'bit',
								rusWord: 'немного',
								rusExplanation: '',
								enTranscription: 'bɪt',
								usTranscription: 'bɪt',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 6,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Preposition',
								partOfSpeech: 'Modifier',
								engWord: 'of',
								rusWord: '',
								rusExplanation:
									'Частица of указывает на принадлежность: немного (чего?) удачи.',
								enTranscription: 'əv',
								usTranscription: 'əv',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 7,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Object',
								engWord: 'luck',
								rusWord: 'удача',
								rusExplanation: '',
								enTranscription: 'lʌk',
								usTranscription: 'lʌk',
							},
						},
						{
							type: 'punctuation',
							text: ', ',
						},
						{
							id: 8,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Verb',
								partOfSpeech: 'Predicate',
								engWord: 'helped',
								rusWord: 'помогли',
								rusExplanation: '',
								enTranscription: 'hɛlpt',
								usTranscription: 'hɛlpt',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 9,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Subject',
								engWord: 'Harry',
								rusWord: 'Гарри',
								rusExplanation: '',
								enTranscription: 'ˈhæri',
								usTranscription: 'ˈhæri',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 10,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Preposition',
								partOfSpeech: 'Modifier',
								engWord: 'to',
								rusWord: '',
								rusExplanation:
									'Частица указывает на неопределённую форму глагола.',
								enTranscription: 'tə',
								usTranscription: 'tə',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 11,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Verb',
								partOfSpeech: 'Predicate',
								engWord: 'find',
								rusWord: 'найти',
								rusExplanation: '',
								enTranscription: 'faɪnd',
								usTranscription: 'faɪnd',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 12,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Article',
								partOfSpeech: 'Modifier',
								engWord: 'a',
								rusWord: '',
								rusExplanation:
									'Артикль, указывающий на неопределённое существительное.',
								enTranscription: 'ə',
								usTranscription: 'ə',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 13,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Object',
								engWord: 'job',
								rusWord: 'работа',
								rusExplanation: '',
								enTranscription: 'dʒɒb',
								usTranscription: 'dʒɑb',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 14,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Conjunction',
								partOfSpeech: 'Conjunction',
								engWord: 'when',
								rusWord: 'когда',
								rusExplanation: '',
								enTranscription: 'wɛn',
								usTranscription: 'wɛn',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 15,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'his',
								rusWord: 'его',
								rusExplanation: '',
								enTranscription: 'hɪz',
								usTranscription: 'hɪz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 16,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Subject',
								engWord: 'parents',
								rusWord: 'родители',
								rusExplanation: '',
								enTranscription: 'ˈpɛərənts',
								usTranscription: 'ˈpɛrənts',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 17,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Verb',
								partOfSpeech: 'Predicate',
								engWord: 'died',
								rusWord: 'умерли',
								rusExplanation: '',
								enTranscription: 'daɪd',
								usTranscription: 'daɪd',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 18,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Adverb',
								partOfSpeech: 'Modifier',
								engWord: 'just',
								rusWord: 'всего через',
								rusExplanation: '',
								enTranscription: 'dʒʌst',
								usTranscription: 'dʒəst',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 19,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Adjective',
								partOfSpeech: 'Modifier',
								engWord: 'two',
								rusWord: 'два',
								rusExplanation: '',
								enTranscription: 'tuː',
								usTranscription: 'tu',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 20,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Object',
								engWord: 'years',
								rusWord: 'года',
								rusExplanation: '',
								enTranscription: 'jɪəz',
								usTranscription: 'jɪrz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 21,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Preposition',
								partOfSpeech: 'Modifier',
								engWord: 'after',
								rusWord: 'после (того как)',
								rusExplanation: '',
								enTranscription: 'ˈɑːftə',
								usTranscription: 'ˈæftər',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 22,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'he',
								rusWord: 'он',
								rusExplanation: '',
								enTranscription: 'hiː',
								usTranscription: 'hi',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 23,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Verb',
								partOfSpeech: 'Predicate',
								engWord: 'finished',
								rusWord: 'закончил',
								rusExplanation: '',
								enTranscription: 'ˈfɪnɪʃt',
								usTranscription: 'ˈfɪnɪʃt',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 24,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Noun',
								partOfSpeech: 'Object',
								engWord: 'school',
								rusWord: 'школа',
								rusExplanation: '',
								enTranscription: 'skuːl',
								usTranscription: 'skul',
							},
						},
						{
							type: 'punctuation',
							text: '. ',
						},
					],
					phrases: [
						{ phraseId: 1, grammar: [{ type: GrammarAliases.DemonstrativePronouns }] },
						{
							phraseId: 2,
							grammar: [
								{ type: GrammarAliases.Noun },
								{ type: GrammarAliases.PluralOfNouns },
							],
						},
					],
					sentence: {
						eng: 'These talents, and a bit of luck, helped Harry to find a job when his parents died just two years after he finished school.',
						rus: 'Эти таланты и немного удачи помогли Гарри найти работу, когда его родители умерли всего через два года после окончания школы.',
					},
				},
			],
		},
		{
			type: 'paragraph',
			sentences: [
				{
					type: 'sentence',
					id: 2,
					sentenceParts: [
						{
							id: 1,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'He',
								rusWord: 'Он',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 2,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'went',
								rusWord: 'ушёл',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 3,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'on',
								rusWord: 'на',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 4,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'to',
								rusWord: '',
								rusExplanation:
									'Частица указывает на неопределённую форму глагола.',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 5,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'win',
								rusWord: 'выиграть',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 6,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'the',
								rusWord: '',
								rusExplanation:
									'Частица указывает на определённое существительное.',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 7,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'final',
								rusWord: 'финал',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: '. ',
						},
					],
					phrases: [],
					sentence: {
						eng: 'He went on to win the final.',
						rus: 'Он одержал победу в финале.',
					},
				},
				{
					type: 'sentence',
					id: 3,
					sentenceParts: [
						{
							id: 1,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'I',
								rusWord: 'Я',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 2,
							type: 'word',
							phraseIds: [1],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: "don't",
								rusWord: 'не',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 3,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'have',
								rusWord: 'имею',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 4,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Article',
								partOfSpeech: 'Modifier',
								engWord: 'a',
								rusWord: '',
								rusExplanation:
									'Артикль, указывающий на неопределённое существительное.',
								enTranscription: 'ə',
								usTranscription: 'ə',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 5,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'few',
								rusWord: 'несколько',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 6,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'years',
								rusWord: 'лет',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: '. ',
						},
					],
					phrases: [{ phraseId: 1, grammar: [{ type: GrammarAliases.AbbreviatedForm }] }],
					sentence: {
						eng: "I don't have a few years.",
						rus: 'У меня нет несколько лет.',
					},
				},
				{
					type: 'sentence',
					id: 4,
					sentenceParts: [
						{
							id: 7,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'I',
								rusWord: 'Я',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 8,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'wish',
								rusWord: 'желаю',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 9,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'to',
								rusWord: '',
								rusExplanation: 'Указывает на движение в каком-то направлении',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 10,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Article',
								partOfSpeech: 'Modifier',
								engWord: 'hell',
								rusWord: 'ад',
								rusExplanation: '',
								enTranscription: 'ə',
								usTranscription: 'ə',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 11,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'I',
								rusWord: 'я',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: ' ',
						},
						{
							id: 12,
							type: 'word',
							phraseIds: [],
							word: {
								partOfSentence: 'Pronoun',
								partOfSpeech: 'Subject',
								engWord: 'did',
								rusWord: 'сделал',
								rusExplanation: '',
								enTranscription: 'ðiːz',
								usTranscription: 'ðiz',
							},
						},
						{
							type: 'punctuation',
							text: '. ',
						},
					],
					phrases: [],
					sentence: {
						eng: 'I wish to hell I did.',
						rus: 'Я бы очень хотел это сделать.',
					},
				},
			],
		},
	],
}
